### ISSUE TITLE
BO Sextupole Model03 Simulation

### ISSUE THREAD

**Issue by LuanaVilela** [lnls-ima/bo-sextupoles#1]
Injection Current (6.75 A):
 bo-sextupoles/model-03/simulation/2017-01-05_BO_Sextupole_Model03_Sim_X=-20_20mm_Z=-300_300mm_Imc=6.75A.txt 

Extraction Current (135 A):
 bo-sextupoles/model-03/simulation/2017-01-05_BO_Sextupole_Model03_Sim_X=-20_20mm_Z=-300_300mm_Imc=135A.txt 

Maximum Gradient (142 A):
 bo-sextupoles/model-03/simulation/2017-01-05_BO_Sextupole_Model03_Sim_X=-20_20mm_Z=-300_300mm_Imc=142A.txt

**Comment by xresende** [comment]
all 3 fmaps analyzed. +4.98% SL above nominal value is close enough to +5% spec. 
multipoles are also ok.
